version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(funcName)s:%(lineno)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: default
  file:
    class: logging.handlers.RotatingFileHandler
    filename: ../data_agent.log
    formatter: default
loggers:
  root:
    level: INFO
    handlers: [ console ]
  framework:
    level: INFO
    propagate: false
    handlers: [ console ]
  data_agent:
    level: INFO
    propagate: false
    handlers: [ console ]
  uvicorn:
    level: INFO
    propagate: false
    handlers: [ file ]
  httpx:
    level: ERROR
    propagate: false
    handlers: [ file ]
